import printersData from "../../../data/printers";
import CommonElements from "../../locators/CommonElements";
import SupportElements from "../../locators/10_support/SupportElements";
import supportsData from "../../../data/supports";
import HomePageMenuElements from "../../locators/03_homepageMenu/HomePageMenuElements";

class SupportActions{
    openSupportTab(){
        cy.get(HomePageMenuElements.cssBlock_CmsComponent).invoke('show')
        cy.contains(supportsData.support.main).click({force:true});
    };
    openInkJetProphotoPrinters(){
        cy.get(HomePageMenuElements.cssBlock_CmsComponent).invoke('show')
        cy.contains(printersData.inkJet.prophoto).click({force:true});
    };
    clickBtnAndDownloadTheFile(){
        cy.get('.btn.btn-primary').eq(3).click();
    };
    clickBtnAndDownloadTheDocFile(){
        cy.get('.btn.btn-primary').eq(11).click();
    };
    openFaqTabByClickOnABtn(){
        cy.get(SupportElements.cssTab_Faq).click();
    };
    typeTextToSearchInputAndSearch(){
        cy.get(SupportElements.cssInput_SearchField).click().type(supportsData.support.search);
        cy.get(SupportElements.cssBtn_SearchBtn).click();
    };
    clickSecondResult(){
      cy.get(SupportElements.cssList_FAQsSecondElement).click();
    };
    clickThirdResult(){
        cy.get(SupportElements.cssList_FAQsThirdElement).click();
    };
    openManualsTabByClickOnABtn(){
        cy.get(SupportElements.cssTab_ManualsDocs).click();
    };
    openOptionsTabByClickOnABtn(){
        cy.get(SupportElements.cssTab_Warranty).click();
    };
    openToggleOfADownloadTab(){
        cy.get(SupportElements.cssToggle_SupportResource).eq(0).click();
    };
    openToggleOfADocsTab(){
        cy.get(SupportElements.cssToggle_SupportResource).eq(7).click();
    };
    clickRegisterNowBtn(){
        cy.get(SupportElements.cssBtn_RegisterNow).click();
    };
    clickCheckYourWarrantyBtn(){
      cy.get(SupportElements.cssBtn_Button).eq(10).click();
    };
    clickCheckExtendedWarrantyBtn(){
        cy.get(SupportElements.cssBtn_Button).eq(11).click();
    };
    clickContactUsButton(){
      cy.get(SupportElements.cssTab_ContactUs).click();
    };
    clickChatNowBtn(){
        cy.get(SupportElements.cssBtn_ChatNow).click();
    };
    clickOnFindRepairButton(){
        cy.wait(2000);
      cy.get(SupportElements.cssBtn_FindRepairCenter).click({force:true});
    };
    clickCloseBtnToCloseWidget(){
      cy.get(SupportElements.cssWidget_CloseWindow).click();
    };
    selectOperatingSystemMac(){
      cy.get(SupportElements.idSelect_OperatingSystems).select("macOS 11 (Big Sur)", {force:true});
    };
    selectOperatingSystemLinux(){
        cy.get(SupportElements.idSelect_OperatingSystems).select("Linux", {force:true});
    };
    selectOperatingSystemWindows(){
        cy.get(SupportElements.idSelect_OperatingSystems).select("Windows XP 64-bit", {force:true});
    };
    clickGoBtn(){
        cy.get(SupportElements.cssBtn_Go).click();
    };
    goToPrintersHomePage(){
      cy.get(SupportElements.cssBtn_PrintersHomePage).click();
    };
    openSupportPage(){
        cy.get(SupportElements.cssLink_Support).click();
    };
    performSearchByProductName(){
      cy.get(SupportElements.cssInput_ProductName).click().type(supportsData.support.searchName);
      cy.get(SupportElements.cssBtn_Search).click();
    };
    openFindPrinterFromSearchResults(){
        cy.get(SupportElements.cssBtn_SearchResult).click();
    }
    performSearchBySerialNumber(){
      cy.get(SupportElements.cssInput_SerialNumber).click().type(supportsData.support.searchSerial)
        cy.wait(500)
        cy.get(SupportElements.cssBtn_Check).click({force:true});
    };
    clickSupportBtnFromPLP(){
        cy.get(SupportElements.cssBtn_SupportPLP).first().click()
    };
    performSearchByPartialPrintersName(){
        cy.get(SupportElements.cssInput_ProductName).click().type(supportsData.support.partialName, {delay:100});
    };
    selectSecondPrinterAndClick(){
      cy.get(SupportElements.cssDropdown_SearchAuto).get("li").get(CommonElements.cssLink_SearchResult).eq(1).click();
    };
    performSearchBySerialNumberForWarrantyCheck(){
        cy.get(SupportElements.cssInput_SerialNumber).click().type(supportsData.support.serial1);
        cy.get(SupportElements.cssBtn_Check).click({force:true});
    };
    performSearchBySerialNumberFor1SubscriptionCheck(){
        cy.get(SupportElements.cssInput_SerialNumber).click().type(supportsData.support.serial2);
        cy.get(SupportElements.cssBtn_Check).click({force:true});
    };
    performSearchBySerialNumberFor3SubscriptionsCheck(){
        cy.get(SupportElements.cssInput_SerialNumber).click().type(supportsData.support.serial5);
        cy.get(SupportElements.cssBtn_Check).click({force:true});
    };
    performSearchBySerialNumberForInfoCheck(){
        cy.get(SupportElements.cssInput_SerialNumber).click().type(supportsData.support.serial3);
        cy.get(SupportElements.cssBtn_Check).click({force:true});
    };
    performSearchBySerialNumberForCheckingOfAnError(){
        cy.get(SupportElements.cssInput_SerialNumber).click().type(supportsData.support.serial4);
        cy.get(SupportElements.cssBtn_Check).click({force:true});
    };
}
export default SupportActions